#!/usr/bin/env ruby
ENV['RAILS_ENV'] ||= 'test'

dummy_root = File.expand_path("../spec/dummy/rails-4.1.9", File.dirname(__FILE__))

begin
  load File.expand_path("../spring", __FILE__) if File.exists?(dummy_root)
rescue LoadError
end
require 'bundler/setup'

require 'pageflow/support'
Pageflow::Dummy.setup

load Gem.bin_path('rspec-core', 'rspec')
